In [ ]:
!pip install --upgrade kmodes

In [ ]:
import numpy as np
from kmodes.kmodes import KModes

# random categorical data
data = np.random.choice(20, (100, 10))

km = KModes(n_clusters=4, init='Huang', n_init=5, verbose=1)

clusters = km.fit_predict(data)

# Print the cluster centroids
print(km.cluster_centroids_)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 24, cost: 803.0
Run 1, iteration: 2/100, moves: 0, cost: 803.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 23, cost: 800.0
Run 2, iteration: 2/100, moves: 3, cost: 800.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 20, cost: 799.0
Run 3, iteration: 2/100, moves: 6, cost: 799.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 23, cost: 802.0
Run 4, iteration: 2/100, moves: 2, cost: 802.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 20, cost: 796.0
Run 5, iteration: 2/100, moves: 8, cost: 794.0
Run 5, iteration: 3/100, moves: 1, cost: 794.0
Best run was number 5
[[ 1 12 12 10 11 16  1 11  4  8]
 [16  8 19 19 19 19  2 

In [ ]:
import prince
dataset = pd.read_csv('https://raw.githubusercontent.com/MaxHalford/prince/master/prince/datasets/decathlon.csv', index_col = 0)
dataset

100m  Long.jump  Shot.put  High.jump   400m  110m.hurdle  \
SEBRLE       11.04       7.58     14.83       2.07  49.81        14.69   
CLAY         10.76       7.40     14.26       1.86  49.37        14.05   
KARPOV       11.02       7.30     14.77       2.04  48.37        14.09   
BERNARD      11.02       7.23     14.25       1.92  48.93        14.99   
YURKOV       11.34       7.09     15.19       2.10  50.42        15.31   
WARNERS      11.11       7.60     14.31       1.98  48.68        14.23   
ZSIVOCZKY    11.13       7.30     13.48       2.01  48.62        14.17   
McMULLEN     10.83       7.31     13.76       2.13  49.91        14.38   
MARTINEAU    11.64       6.81     14.57       1.95  50.14        14.93   
HERNU        11.37       7.56     14.41       1.86  51.10        15.06   
BARRAS       11.33       6.97     14.09       1.95  49.48        14.48   
NOOL         11.33       7.27     12.68       1.98  49.20        15.29   
BOURGUIGNON  11.36       6.80     13.46       1.86  51.16        15.67   
Sebrle       10.85       7.84     16.36       2.12  48.36        14.05   
Clay         10.44       7.96     15.23       2.06  49.19        14.13   
Karpov       10.50       7.81     15.93       2.09  46.81        13.97   
Macey        10.89       7.47     15.73       2.15  48.97        14.56   
Warners      10.62       7.74     14.48       1.97  47.97        14.01   
Zsivoczky    10.91       7.14     15.31       2.12  49.40        14.95   
Hernu        10.97       7.19     14.65       2.03  48.73        14.25   
Nool         10.80       7.53     14.26       1.88  48.81        14.80   
Bernard      10.69       7.48     14.80       2.12  49.13        14.17   
Schwarzl     10.98       7.49     14.01       1.94  49.76        14.25   
Pogorelov    10.95       7.31     15.10       2.06  50.79        14.21   
Schoenbeck   10.90       7.30     14.77       1.88  50.30        14.34   
Barras       11.14       6.99     14.91       1.94  49.41        14.37   
Smith        10.85       6.81     15.24       1.91  49.27        14.01   
Averyanov    10.55       7.34     14.44       1.94  49.72        14.39   
Ojaniemi     10.68       7.50     14.97       1.94  49.12        15.01   
Smirnov      10.89       7.07     13.88       1.94  49.11        14.77   
Qi           11.06       7.34     13.55       1.97  49.65        14.78   
Drews        10.87       7.38     13.07       1.88  48.51        14.01   
Parkhomenko  11.14       6.61     15.69       2.03  51.04        14.88   
Terek        10.92       6.94     15.15       1.94  49.56        15.12   
Gomez        11.08       7.26     14.57       1.85  48.61        14.41   
Turi         11.08       6.91     13.62       2.03  51.67        14.26   
Lorenzo      11.10       7.03     13.22       1.85  49.34        15.38   
Karlivans    11.33       7.26     13.30       1.97  50.54        14.98   
Korkizoglou  10.86       7.07     14.81       1.94  51.16        14.96   
Uldal        11.23       6.99     13.53       1.85  50.95        15.09   
Casarsa      11.36       6.68     14.92       1.94  53.20        15.39   

             Discus  Pole.vault  Javeline   1500m  Rank  Points Competition  
SEBRLE        43.75        5.02     63.19  291.70     1    8217    Decastar  
CLAY          50.72        4.92     60.15  301.50     2    8122    Decastar  
KARPOV        48.95        4.92     50.31  300.20     3    8099    Decastar  
BERNARD       40.87        5.32     62.77  280.10     4    8067    Decastar  
YURKOV        46.26        4.72     63.44  276.40     5    8036    Decastar  
WARNERS       41.10        4.92     51.77  278.10     6    8030    Decastar  
ZSIVOCZKY     45.67        4.42     55.37  268.00     7    8004    Decastar  
McMULLEN      44.41        4.42     56.37  285.10     8    7995    Decastar  
MARTINEAU     47.60        4.92     52.33  262.10     9    7802    Decastar  
HERNU         44.99        4.82     57.19  285.10    10    7733    Decastar  
BARRAS        42.10        4.72     55.40  282.

In [ ]:
decastar = dataset.query('Competition == "Decastar"')
decastar.drop('Competition', axis = 1, inplace = True)
decastar

<ipython-input-45-0628d1adf1fd>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  decastar.drop('Competition', axis = 1, inplace = True)


100m  Long.jump  Shot.put  High.jump   400m  110m.hurdle  \
SEBRLE       11.04       7.58     14.83       2.07  49.81        14.69   
CLAY         10.76       7.40     14.26       1.86  49.37        14.05   
KARPOV       11.02       7.30     14.77       2.04  48.37        14.09   
BERNARD      11.02       7.23     14.25       1.92  48.93        14.99   
YURKOV       11.34       7.09     15.19       2.10  50.42        15.31   
WARNERS      11.11       7.60     14.31       1.98  48.68        14.23   
ZSIVOCZKY    11.13       7.30     13.48       2.01  48.62        14.17   
McMULLEN     10.83       7.31     13.76       2.13  49.91        14.38   
MARTINEAU    11.64       6.81     14.57       1.95  50.14        14.93   
HERNU        11.37       7.56     14.41       1.86  51.10        15.06   
BARRAS       11.33       6.97     14.09       1.95  49.48        14.48   
NOOL         11.33       7.27     12.68       1.98  49.20        15.29   
BOURGUIGNON  11.36       6.80     13.46       1.86  51.16        15.67   

             Discus  Pole.vault  Javeline  1500m  Rank  Points  
SEBRLE        43.75        5.02     63.19  291.7     1    8217  
CLAY          50.72        4.92     60.15  301.5     2    8122  
KARPOV        48.95        4.92     50.31  300.2     3    8099  
BERNARD       40.87        5.32     62.77  280.1     4    8067  
YURKOV        46.26        4.72     63.44  276.4     5    8036  
WARNERS       41.10        4.92     51.77  278.1     6    8030  
ZSIVOCZKY     45.67        4.42     55.37  268.0     7    8004  
McMULLEN      44.41        4.42     56.37  285.1     8    7995  
MARTINEAU     47.60        4.92     52.33  262.1     9    7802  
HERNU         44.99        4.82     57.19  285.1    10    7733  
BARRAS        42.10        4.72     55.40  282.0    11    7708  
NOOL          37.92        4.62     57.44  266.6    12    7651  
BOURGUIGNON   40.49        5.02     54.68  291.7    13    7313

In [ ]:
 pca = prince.PCA(n_components=5)
 pca

PCA(n_components=5)

In [ ]:
pca = pca.fit(decastar)

In [ ]:
pca.transform(decastar).tail()


0         1         2         3         4
MARTINEAU    2.057746 -0.359840  0.769058  2.526179 -1.253632
HERNU        1.292636 -1.310779 -0.450277  0.068702  0.980883
BARRAS       1.460324  0.631933 -0.432883  0.552382 -0.080804
NOOL         2.850556  1.884748  0.272068 -1.870311 -0.300863
BOURGUIGNON  4.273110 -1.524455 -1.475070 -0.147090  0.805596

In [ ]:
pca.plot(dataset)

AttributeError: 'PCA' object has no attribute 'plot'

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import plotly.express as px
import seaborn as sns
from sklearn import datasets
import mca
from prince import MCA


df = pd.read_csv('https://raw.githubusercontent.com/shekharbiswas/MHC/main/mental-heath-in-tech-2016_20161114.csv')

# MHC : mental health condition


df = df.rename(columns={'What is your gender?': 'Gender',
                        'What is your age?': 'Age',
                        'What country do you live in?': 'Country',
                        'What US state or territory do you live in?': 'US_state_live',
                        'Do you work remotely?': 'Remote',
                        'What US state or territory do you work in?': 'US_state_work',
                        'Which of the following best describes your work position?' : 'work_pos',
                        'Have you been diagnosed with a mental health condition by a medical professional?' : 'Diagnosed_mhc_by_medical_professional',
                        'Are you self-employed?' : 'self-employed',
                        "Does your employer provide mental health benefits as part of healthcare coverage?" : "healthcare_coverage"
                        })


df.head(5)

self-employed How many employees does your company or organization have?  \
0              0                                             26-100           
1              0                                             Jun-25           
2              0                                             Jun-25           
3              1                                                NaN           
4              0                                             Jun-25           

   Is your employer primarily a tech company/organization?  \
0                                                1.0         
1                                                1.0         
2                                                1.0         
3                                                NaN         
4                                                0.0         

   Is your primary role within your company related to tech/IT?  \
0                                                NaN              
1                                                NaN              
2                                                NaN              
3                                                NaN              
4                                                1.0              

               healthcare_coverage  \
0  Not eligible for coverage / N/A   
1                               No   
2                               No   
3                              NaN   
4                              Yes   

  Do you know the options for mental health care available under your employer-provided coverage?  \
0                                                NaN                                                
1                                                Yes                                                
2                                                NaN                                                
3                                                NaN                                                
4                                                Yes                                                

  Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?  \
0                                                 No                                                                                       
1                                                Yes                                                                                       
2                                                 No                                                                                       
3                                                NaN                                                                                       
4                                                 No                                                                                       

  Does your employer offer resources to learn more about mental health concerns and options for seeking help?  \
0                                                 No                                                            
1                                                Yes                                                            
2                                                 No                                                            
3                                                NaN                                                            
4                                                 No                                                            

  Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?  \
0                                       I don't know                                                                                               
1                                                Yes                                                

In [ ]:
df.dtypes

self-employed                                                     int64
How many employees does your company or organization have?       object
Is your employer primarily a tech company/organization?         float64
Is your primary role within your company related to tech/IT?    float64
healthcare_coverage                                              object
                                                                 ...   
US_state_live                                                    object
What country do you work in?                                     object
US_state_work                                                    object
work_pos                                                         object
Remote                                                           object
Length: 63, dtype: object

**MCA** vs **PCA**


Now, regarding Multiple CA. It is CA with more than 2 categorical variables. MCA is the dim. reduction analysis for nominal categorical variables. PCA is the linear dim. reduction analysis for scale (interval) variables. There exist the more general method Categorical PCA (CATPCA). Now, MCA can be seen a special case of it: "CATPCA with nominal level of quantification applied to all the (nominal) variables". If all the variables are dichotomous (such as YES/NO) MCA and PCA become essentially identical, though their customary results output may differ in form.



In [ ]:
counts = pd.read_table('https://raw.githubusercontent.com/esafak/mca/master/data/burgundies.csv', sep=',', skiprows=1, index_col=0, header=0)

In [ ]:
counts


oak_type  fruity_1  fruity_1.1  woody_1  woody_1.1  woody_1.2  coffee  \
Wine                                                                          
W1           1         1           0        0          0          1       0   
W2           2         0           1        0          1          0       1   
W3           2         0           1        1          0          0       1   
W4           2         0           1        1          0          0       1   
W5           1         1           0        0          0          1       0   
W6           1         1           0        0          1          0       0   

      coffee.1  fruity_2  fruity_2.1  ...  vanillin.1  vanillin.2  woody_2  \
Wine                                  ...                                    
W1           1         1           0  ...           0           1        0   
W2           0         0           1  ...           1           0        1   
W3           0         0           1  ...           0           0        1   
W4           0         0           1  ...           0           0        1   
W5           1         1           0  ...           0           1        0   
W6           1         1           0  ...           1           0        0   

      woody_2.1  fruity_3  fruity_3.1  buttery  buttery.1  woody_3  woody_3.1  
Wine                                                                           
W1            1         0           1        0          1        0          1  
W2            0         0           1        1          0        1          0  
W3            0         0           1        1          0        1          0  
W4            0         1           0        1          0        1          0  
W5            1         1           0        0          1        0          1  
W6            1         1           0        0          1        0          1  

[6 rows x 23 columns]

In [ ]:
mca_counts = mca.MCA(counts.drop('oak_type', axis=1))

In [ ]:
mca_counts

In [ ]:
print(mca_counts.fs_r(1))

[[ 0.87127085  0.11448396 -0.09250792]
 [-0.7209849  -0.22896791 -0.083259  ]
 [-0.93238083  0.11448396 -0.02206285]
 [-0.87127085  0.11448396  0.09250792]
 [ 0.93238083  0.11448396  0.02206285]
 [ 0.7209849  -0.22896791  0.083259  ]]


In [ ]:
print(mca_counts.L)

[0.71608871 0.02621315 0.00532552]


In [ ]:
df.corr()

<ipython-input-17-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


self-employed  \
self-employed                                            1.000000   
Is your employer primarily a tech company/organ...            NaN   
Is your primary role within your company relate...            NaN   
Do you have medical coverage (private insurance...            NaN   
Do you have previous employers?                         -0.022451   
Have you ever sought treatment for a mental hea...       0.049432   
Age                                                      0.111676   

                                                    Is your employer primarily a tech company/organization?  \
self-employed                                                                                     NaN         
Is your employer primarily a tech company/organ...                                           1.000000         
Is your primary role within your company relate...                                                NaN         
Do you have medical coverage (private insurance...                                                NaN         
Do you have previous employers?                                                              0.038714         
Have you ever sought treatment for a mental hea...                                          -0.000934         
Age                                                                                         -0.079585         

                                                    Is your primary role within your company related to tech/IT?  \
self-employed                                                                                     NaN              
Is your employer primarily a tech company/organ...                                                NaN              
Is your primary role within your company relate...                                           1.000000              
Do you have medical coverage (private insurance...                                                NaN              
Do you have previous employers?                                                              0.045161              
Have you ever sought treatment for a mental hea...                                           0.020298              
Age                                                                                         -0.053179              

                                                    Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?  \
self-employed                                                                                     NaN                                                                       
Is your employer primarily a tech company/organ...                                                NaN                                                                       
Is your primary role within your company relate...                                                NaN                                                                       
Do you have medical coverage (private insurance...                                           1.000000                                                                       
Do you have previous employers?                                                              0.053584                                                                       
Have you ever sought treatment for a mental hea...                                           0.085889                                                                       
Age                                                                                         -0.016832                                                                       

                                                    Do you have previous employers?  \
self-employed                                                             -0.022451   
Is your employer primarily a tech company/organ...                         0.038714   
Is your primary role within your co

In [ ]:
df

self-employed  \
0                 0   
1                 0   
2                 0   
3                 1   
4                 0   
...             ...   
1428              1   
1429              1   
1430              0   
1431              0   
1432              0   

     How many employees does your company or organization have?  \
0                                                26-100           
1                                                Jun-25           
2                                                Jun-25           
3                                                   NaN           
4                                                Jun-25           
...                                                 ...           
1428                                                NaN           
1429                                                NaN           
1430                                            100-500           
1431                                            100-500           
1432                                            100-500           

      Is your employer primarily a tech company/organization?  \
0                                                   1.0         
1                                                   1.0         
2                                                   1.0         
3                                                   NaN         
4                                                   0.0         
...                                                 ...         
1428                                                NaN         
1429                                                NaN         
1430                                                1.0         
1431                                                0.0         
1432                                                1.0         

      Is your primary role within your company related to tech/IT?  \
0                                                   NaN              
1                                                   NaN              
2                                                   NaN              
3                                                   NaN              
4                                                   1.0              
...                                                 ...              
1428                                                NaN              
1429                                                NaN              
1430                                                NaN              
1431                                                1.0              
1432                                                NaN              

                  healthcare_coverage  \
0     Not eligible for coverage / N/A   
1                                  No   
2                                  No   
3                                 NaN   
4                                 Yes   
...                               ...   
1428                              NaN   
1429                              NaN   
1430                              Yes   
1431                     I don't know   
1432                              Yes   

     Do you know the options for mental health care available under your employer-provided coverage?  \
0                                                   NaN                                                
1                                                   Yes                                                
2                                                   NaN                                                
3                                                   NaN                                                
4                                                   Yes                                                
...                                                 ...                                                
1428                                                NaN                          

In [ ]:

mca = MCA(n_components=80, n_iter=50, copy=True, check_input=True, random_state=42)

In [ ]:
import prince
dataset = prince.datasets.load_decathlon()
dataset

AttributeError: module 'prince' has no attribute 'datasets'

In [ ]:
df['work_pos'].value_counts()[0:10]

Back-end Developer                        263
Front-end Developer                       125
Other                                     112
Supervisor/Team Lead                       68
Back-end Developer|Front-end Developer     61
DevOps/SysAdmin                            54
One-person shop                            50
Executive Leadership                       46
Front-end Developer|Back-end Developer     40
Support                                    34
Name: work_pos, dtype: int64

In [ ]:
df['Diagnosed_mhc_by_medical_professional']

0       Yes
1       Yes
2        No
3       Yes
4       Yes
       ... 
1428     No
1429    Yes
1430    Yes
1431    Yes
1432     No
Name: Diagnosed_mhc_by_medical_professional, Length: 1433, dtype: object

In [ ]:
df['If yes, what condition(s) have you been diagnosed with?'].value_counts()[0:10]

Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)                                             117
Mood Disorder (Depression, Bipolar Disorder, etc)                                                                                                 102
Anxiety Disorder (Generalized, Social, Phobia, etc)                                                                                                47
Anxiety Disorder (Generalized, Social, Phobia, etc)|Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder     26
Mood Disorder (Depression, Bipolar Disorder, etc)|Attention Deficit Hyperactivity Disorder                                                         22
Attention Deficit Hyperactivity Disorder                                                                                                           18
Anxiety Disorder (Generalized, Social, Phobia, etc)|Attention Deficit Hyperactivity Disorder        